---
AWSTemplateFormatVersion: "2010-09-09"

Description: "PSGalleryExplorer: Control Plane"

Parameters:
  ServiceName:
    Type: String
    Description: 'Name of the service that will be used to tag each resource.'

  BucketName:
    Type: String
    Description: Hard coded S3 bucketname prefix

  ArtifactS3Bucket:
    Type: String
    Description: S3 Bucket for CodePipeline Artifacts

  ArtifactS3KeyPrefix:
    Type: String
    Description: S3 Key Prefix for CodePipeline Artifacts

Resources:

  # Deploys the s3 buckets used for the PSGalleryExplorer project
  PSGES3Buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${ArtifactS3Bucket}.s3.amazonaws.com/${ArtifactS3KeyPrefix}/${FileName}'
        - #AWSRegion: !Ref "AWS::Region"
          ArtifactS3Bucket: !Ref ArtifactS3Bucket
          ArtifactS3KeyPrefix: !Ref ArtifactS3KeyPrefix
          FileName: CloudFormation/PSGalleryExplorer/ChildTemplates/PSGES3Buckets.yml
      TimeoutInMinutes: 5 #make sure it can actually complete in this time period
      Parameters: #much match the parameters of nested template
        ServiceName: !Ref ServiceName
        BucketName: !Ref BucketName
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName