---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AUTOMATED: PSGalleryExplorer: Control Plane'

Parameters:
  ServiceName:
    Type: String
    Description: 'Name of the service that will be used to tag each resource.'

  LMFunctionS3KeyPubXMLMonitor:
    Type: String
    Description: S3 Key for the PubXMLMonitor Lambda function(s) zip file

  LMFunctionHandlerPubXMLMonitor:
    Type: String
    Description: PubXMLMonitor Lambda HANDLER provided by New-AWSPowerShellLambdaPackage during build

  ArtifactS3Bucket:
    Type: String
    Description: S3 Bucket for CodePipeline Artifacts

  ArtifactS3KeyPrefix:
    Type: String
    Description: S3 Key Prefix for CodePipeline Artifacts

Resources:
  # Deploys the s3 buckets used for the PSGalleryExplorer project
  PSGES3Buckets:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub
        - 'https://${ArtifactS3Bucket}.s3.amazonaws.com/${ArtifactS3KeyPrefix}/${FileName}'
        - #AWSRegion: !Ref "AWS::Region"
          ArtifactS3Bucket: !Ref ArtifactS3Bucket
          ArtifactS3KeyPrefix: !Ref ArtifactS3KeyPrefix
          FileName: CloudFormation/PSGalleryExplorer/ChildTemplates/PSGES3Buckets.yml
      TimeoutInMinutes: 5 #make sure it can actually complete in this time period
      Parameters: #much match the parameters of nested template
        ServiceName: !Ref ServiceName
        ResourceType: prod
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName

  # Deploys the alarms used for the PSGalleryExplorer project
  PSGEAlarms:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    DependsOn: PSGES3Buckets
    Properties:
      TemplateURL: !Sub
        - 'https://${ArtifactS3Bucket}.s3.amazonaws.com/${ArtifactS3KeyPrefix}/${FileName}'
        - #AWSRegion: !Ref "AWS::Region"
          ArtifactS3Bucket: !Ref ArtifactS3Bucket
          ArtifactS3KeyPrefix: !Ref ArtifactS3KeyPrefix
          FileName: CloudFormation/PSGalleryExplorer/ChildTemplates/PSGEAlarms.yml
      TimeoutInMinutes: 5 #make sure it can actually complete in this time period
      Parameters: #much match the parameters of nested template
        ServiceName: !Ref ServiceName
        LambdaS3BucketName: !Ref ArtifactS3Bucket
        LMFunctionS3KeyPubXMLMonitor: !Ref LMFunctionS3KeyPubXMLMonitor
        LMFunctionHandlerPubXMLMonitor: !Ref LMFunctionHandlerPubXMLMonitor
        ResourceType: prod
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName

  # Deploys the alarms used for the PSGalleryExplorer project
  PSGESSM:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub
        - 'https://${ArtifactS3Bucket}.s3.amazonaws.com/${ArtifactS3KeyPrefix}/${FileName}'
        - #AWSRegion: !Ref "AWS::Region"
          ArtifactS3Bucket: !Ref ArtifactS3Bucket
          ArtifactS3KeyPrefix: !Ref ArtifactS3KeyPrefix
          FileName: CloudFormation/PSGalleryExplorer/ChildTemplates/PSGESSM.yml
      TimeoutInMinutes: 15 #make sure it can actually complete in this time period
      Parameters: #much match the parameters of nested template
        ServiceName: !Ref ServiceName
        ResourceType: prod
      Tags:
        - Key: ServiceName
          Value: !Ref ServiceName
        - Key: StackName
          Value: !Ref AWS::StackName
