---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AUTOMATED: PSGalleryExplorer - alarms deployment'

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service being deployed. Used for Developer AWS Account Resource Names.

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
  AlarmNumberOfMessagesVisibleUpdatePubXMLDataDlq:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: Alarms if the UpdatePubXMLDataDlq Dead Letter Queue has too many messages
      AlarmName: UpdatePubXMLDataDlq_NumberOfMessagesVisible
      ComparisonOperator: GreaterThanOrEqualToThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: QueueName
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-UpdatePubXMLDataDlqName
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ApproximateNumberOfMessagesVisible
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/SQS
      # OKActions:
      #   - String
      Period: 300
      Statistic: Maximum
      Threshold: 1
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
  AlarmNumberOfMessagesVisibleUpdateGitHubDataDlq:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: Alarms if the GitHubDataDlq Dead Letter Queue has too many messages
      AlarmName: GitHubDataDlq_NumberOfMessagesVisible
      ComparisonOperator: GreaterThanOrEqualToThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: QueueName
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitHubDataDlqName
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ApproximateNumberOfMessagesVisible
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/SQS
      # OKActions:
      #   - String
      Period: 300
      Statistic: Maximum
      Threshold: 1
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html
  AlarmNumberOfMessagesVisibleUpdateGitLabDataDlq:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: Alarms if the GitLabDataDlq Dead Letter Queue has too many messages
      AlarmName: GitLabDataDlq_NumberOfMessagesVisible
      ComparisonOperator: GreaterThanOrEqualToThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: QueueName
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitLabDataDlqName
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ApproximateNumberOfMessagesVisible
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/SQS
      # OKActions:
      #   - String
      Period: 300
      Statistic: Maximum
      Threshold: 1
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String
  #######################################################################
  #######################################################################

  GitHubSMTimedOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: !Sub >-
        ${ServiceName} State Machine has had an execution time out.
        This could be for any reason, investigation is required.
      AlarmName: !Sub ${ServiceName} State Machine EXECUTION TIMED OUT (${AWS::StackName})
      ComparisonOperator: GreaterThanThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: StateMachineArn
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitHubScannerSMDelayStateMachineARN
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ExecutionsTimedOut
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/States
      # OKActions:
      #   - String
      Period: 60
      Statistic: Sum
      Threshold: 0
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  GitHubSMThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: !Sub >-
        ${ServiceName} State Machine has had state transitions
        throttled. This is a limit imposed by AWS Step Functions itself within
        the state machine, not related to throttling of services used as state
        resources, such as AWS Lambda or Fargate.
      AlarmName: !Sub ${ServiceName} State Machine STATE TRANSITION THROTTLE (${AWS::StackName})
      ComparisonOperator: GreaterThanThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: StateMachineArn
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitHubScannerSMDelayStateMachineARN
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ExecutionThrottled
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/States
      # OKActions:
      #   - String
      Period: 60
      Statistic: Sum
      Threshold: 0
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  GitHubSMFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: !Sub >-
        ${ServiceName} State Machine has had an execution failure.
        A state machine execution failure indicates that an error occurred and
        was unable to be caught and handled gracefully. This likely means the
        job failed in some way and that some or all callbacks were unsuccessful.
      AlarmName: !Sub ${ServiceName} State Machine EXECUTION FAILED(${AWS::StackName})
      ComparisonOperator: GreaterThanThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: StateMachineArn
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitHubScannerSMDelayStateMachineARN
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ExecutionsFailed
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/States
      # OKActions:
      #   - String
      Period: 60
      Statistic: Sum
      Threshold: 0
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  GitLabSMTimedOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: !Sub >-
        ${ServiceName} State Machine has had an execution time out.
        This could be for any reason, investigation is required.
      AlarmName: !Sub ${ServiceName} State Machine EXECUTION TIMED OUT (${AWS::StackName})
      ComparisonOperator: GreaterThanThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: StateMachineArn
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitLabScannerSMDelayStateMachineArn
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ExecutionsTimedOut
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/States
      # OKActions:
      #   - String
      Period: 60
      Statistic: Sum
      Threshold: 0
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  GitLabSMThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: !Sub >-
        ${ServiceName} State Machine has had state transitions
        throttled. This is a limit imposed by AWS Step Functions itself within
        the state machine, not related to throttling of services used as state
        resources, such as AWS Lambda or Fargate.
      AlarmName: !Sub ${ServiceName} State Machine STATE TRANSITION THROTTLE (${AWS::StackName})
      ComparisonOperator: GreaterThanThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: StateMachineArn
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitLabScannerSMDelayStateMachineArn
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ExecutionThrottled
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/States
      # OKActions:
      #   - String
      Period: 60
      Statistic: Sum
      Threshold: 0
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

  GitLabSMFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:alertTopic
      AlarmDescription: !Sub >-
        ${ServiceName} State Machine has had an execution failure.
        A state machine execution failure indicates that an error occurred and
        was unable to be caught and handled gracefully. This likely means the
        job failed in some way and that some or all callbacks were unsuccessful.
      AlarmName: !Sub ${ServiceName} State Machine EXECUTION FAILED(${AWS::StackName})
      ComparisonOperator: GreaterThanThreshold
      # DatapointsToAlarm: Integer
      # EvaluateLowSampleCountPercentile: String
      Dimensions:
        - Name: StateMachineArn
          Value:
            Fn::ImportValue: !Sub ${ServiceName}-GitLabScannerSMDelayStateMachineArn
      # EvaluateLowSampleCountPercentile: String
      EvaluationPeriods: 1
      # ExtendedStatistic: String
      # InsufficientDataActions:
      #   - String
      MetricName: ExecutionsFailed
      # Metrics:
      #   - MetricDataQuery
      Namespace: AWS/States
      # OKActions:
      #   - String
      Period: 60
      Statistic: Sum
      Threshold: 0
      # ThresholdMetricId: String
      TreatMissingData: notBreaching
      # Unit: String

Outputs:
  PubXMLDataDlqAlarmName:
    Value: !Ref AlarmNumberOfMessagesVisibleUpdatePubXMLDataDlq

  GitHubDataDlqAlarmName:
    Value: !Ref AlarmNumberOfMessagesVisibleUpdateGitHubDataDlq

  GitLabDataDlqAlarmName:
    Value: !Ref AlarmNumberOfMessagesVisibleUpdateGitLabDataDlq

  GitHubSMTimedOutAlarmName:
    Description: GitHubSMTimedOutAlarm Alarm Name
    Value: !Ref GitHubSMTimedOutAlarm

  GitHubSMTimedOutAlarmARN:
    Description: GitHubSMTimedOutAlarm Alarm ARN
    Value: !GetAtt  GitHubSMTimedOutAlarm.Arn
    Export:
      Name: !Sub ${ServiceName}-GitHubSMTimedOutAlarmARN

  GitHubSMThrottleAlarmName:
    Description: GitHubSMThrottleAlarm Alarm Name
    Value: !Ref GitHubSMThrottleAlarm

  GitHubSMThrottleAlarmARN:
    Description: GitHubSMThrottleAlarm Alarm ARN
    Value: !GetAtt  GitHubSMThrottleAlarm.Arn
    Export:
      Name: !Sub ${ServiceName}-GitHubSMThrottleAlarmARN

  GitHubSMFailureAlarmName:
    Description: GitHubSMFailureAlarm Alarm Name
    Value: !Ref GitHubSMFailureAlarm

  GitHubSMFailureAlarmARN:
    Description: GitHubSMFailureAlarm Alarm ARN
    Value: !GetAtt  GitHubSMFailureAlarm.Arn
    Export:
      Name: !Sub ${ServiceName}-GitHubSMFailureAlarmARN

  GitLabSMTimedOutAlarmName:
    Description: GitLabSMTimedOutAlarm Alarm Name
    Value: !Ref GitLabSMTimedOutAlarm

  GitLabSMTimedOutAlarmARN:
    Description: GitLabSMTimedOutAlarm Alarm ARN
    Value: !GetAtt  GitLabSMTimedOutAlarm.Arn
    Export:
      Name: !Sub ${ServiceName}-GitLabSMTimedOutAlarmARN

  GitLabSMThrottleAlarmName:
    Description: GitLabSMThrottleAlarm Alarm Name
    Value: !Ref GitLabSMThrottleAlarm

  GitLabSMThrottleAlarmARN:
    Description: GitLabSMThrottleAlarm Alarm ARN
    Value: !GetAtt  GitLabSMThrottleAlarm.Arn
    Export:
      Name: !Sub ${ServiceName}-GitLabSMThrottleAlarmARN

  GitLabSMFailureAlarmName:
    Description: GitLabSMFailureAlarm Alarm Name
    Value: !Ref GitLabSMFailureAlarm

  GitLabSMFailureAlarmARN:
    Description: GitLabSMFailureAlarm Alarm ARN
    Value: !GetAtt  GitLabSMFailureAlarm.Arn
    Export:
      Name: !Sub ${ServiceName}-GitLabSMFailureAlarmARN