---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'CICD Deployed: Test SNS role for pipeline verification'

Parameters:
  ProjectName:
    Type: String

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
  TestSNS:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${ProjectName}-TestSNS
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: StackName
          Value: !Ref AWS::StackName

Outputs:

  TestSNSOutput:
    Value: !Ref  TestSNS
    Export:
      Name: !Sub '${ProjectName}-TestSNSArn'
